# Generated by Django 3.2.9 on 2021-11-20 23:45

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Commercial Network name')),
                ('format', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128, verbose_name='Commercial Network format'), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Product name')),
                ('category', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128, verbose_name='Product category'), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=256, verbose_name='Shop address')),
                ('commercial_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='core.commercialnetwork')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_in_shop', models.IntegerField(max_length=99999, verbose_name='Number in shop')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_availability', to='core.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_availability', to='core.shop')),
            ],
        ),
    ]
