# Generated by Django 3.2.9 on 2021-11-21 00:00

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialnetwork',
            name='format',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=128, verbose_name='Commercial Network format'), size=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=128, verbose_name='Product category'), size=None),
        ),
    ]
