# Generated by Django 3.2.6 on 2021-11-21 22:26

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialnetwork',
            name='format',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=128, verbose_name='Format'), size=None),
        ),
        migrations.AlterField(
            model_name='commercialnetwork',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(max_length=256, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='format',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Format'),
        ),
    ]
