# Generated by Django 3.2.9 on 2021-11-21 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211121_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='format_index',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Shop format'),
        ),
    ]
