# Generated by Django 3.2.6 on 2021-11-21 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211121_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='format',
            field=models.CharField(default='1200', max_length=128, verbose_name='Format'),
            preserve_default=False,
        ),
    ]
