# Generated by Django 3.2.9 on 2021-11-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_shop_format_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='format_index',
        ),
        migrations.AddField(
            model_name='shop',
            name='format',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Shop format'),
        ),
    ]
