# Generated by Django 3.2.6 on 2021-11-21 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_shop_format'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commercialnetwork',
            old_name='format',
            new_name='network_format',
        ),
    ]
